a=10
b=20
print(a)
print(b)

In [5]:
a=10
b=20
print(a+b)

30


In [6]:
a=10
b=20
print("The value of b is",b)

The value of b is 20


In [7]:
a=input("enter")


enter 25


In [8]:
a=input("enter")
print(a)


enter 25


25


In [9]:
a=float(input("enter the value"))
print(a)


enter the value 47


47.0


### Operators

#### Arithmetic

In [13]:
a=10
b=30
print("Addition",a+b)

Addition 40


In [14]:
print("sub",a-b)


sub -20


In [15]:
print("divi",a/b)


divi 0.3333333333333333


In [16]:
print("modulus",a%b)


modulus 10


In [17]:
print("floor division",a//b)


floor division 0


In [18]:
print("Exponent",a**2)


Exponent 100


#### Assignment 

In [19]:
a=10
a+=20 # a=a+20
print(a)

30


In [20]:
a=10
a-=20 
print(a)

-10


In [20]:
a=10
a-=20 
print(a)

-10


In [20]:
a=10
a-=20 
print(a)

-10


In [21]:
a=10
a*=20 
print(a)

200


In [22]:
a=10
a/=20 
print(a)

0.5


In [23]:
a=10
a//=20 
print(a)

0


In [24]:
a=10
a%=20 
print(a)

10


#### Bitswise

In [25]:
a=2
b=3 
print(a&b)

2


In [26]:
print(a|b)

3


In [28]:
print(a>>2)

0

In [29]:
print(a<<2)

8


In [2]:
list1=[23,34,45,56]
list1.append(34)
print(list1)

[23, 34, 45, 56, 34]


In [5]:
list1=[23,34,45,56]
list1.extend([23,45,65,54])
print(list1)
list1.insert(0,26)
print(list1)

[23, 34, 45, 56, 23, 45, 65, 54]
[26, 23, 34, 45, 56, 23, 45, 65, 54]


##### sorting and Reversing the list

In [7]:
list3 = [32,1,89,45,2,6]

list3.reverse()
print(list3)

list3.sort()
print(list3)

list3.sort(reverse=True)#parameters
print(list3)

[6, 2, 45, 89, 1, 32]
[1, 2, 6, 32, 45, 89]
[89, 45, 32, 6, 2, 1]


#### Slicing in list

In [9]:
list4 =[56,43,32,21,20,67]

print(list4[5])

print(list4[0])

print(list4[4])

print(list4[3])

print(list4[0:3]) # 3 is ending index doesnt print

print(list4[2:5])

print(list4[-1]) 

print(list4[-3:-1]) 

print(list4[:])

print(list4[::3]) #step index

67
56
20
21
[56, 43, 32]
[32, 21, 20]
67
[21, 20]
[56, 43, 32, 21, 20, 67]
[56, 21]


#### Membership Operators


In [10]:
numbers = [1,2,3,4,5]

print( 3 in numbers )

print( 10 in numbers)

print(10 not in numbers)

True
False
True


### identity operators

In [11]:
a = 10
b = 20

print (a is b)
print (a is not b)

False
True


### Tuple

In [12]:
a = (10,13,15,26,56,'sujith')
a

(10, 13, 15, 26, 56, 'sujith')

In [13]:
days = ( "mon","tue","wed","thurs","fri","sat","sun")
days


('mon', 'tue', 'wed', 'thurs', 'fri', 'sat', 'sun')

In [14]:
len(days)

7

In [16]:
month1 = ('jan','feb','march','april','may','jun','july','august','spet','oct')
month2 = ('nov','dec')

In [19]:
month = month1 + month2
print(month)

('jan', 'feb', 'march', 'april', 'may', 'jun', 'july', 'august', 'spet', 'oct', 'nov', 'dec')


### creating set

In [20]:
day={'mon','tue','wed','thu','fri','sat'}
week_end={'sat','sun'}

In [21]:
day={'mon','tue','wed','thu','fri','sat','sat'}
day

{'fri', 'mon', 'sat', 'thu', 'tue', 'wed'}

In [22]:
new_days=day.union(week_end)
new_days


{'fri', 'mon', 'sat', 'sun', 'thu', 'tue', 'wed'}

In [24]:
day.symmetric_difference(week_end)

{'fri', 'mon', 'sun', 'thu', 'tue', 'wed'}

#### Slcinig


In [1]:
my_set = {10, 20, 30, 40, 50}

In [2]:
my_list = list(my_set)
sliced_part = my_list[1:4]
print(sliced_part)

[20, 40, 10]


#### Some Other Function

In [5]:
x1 = {1,2,3}
x1.update({4,5})
x1

{1, 2, 3, 4, 5}

In [10]:
day={'mon','tue','wed','thur','fri','sat','sun'}
print(day)

{'wed', 'tue', 'thur', 'sun', 'mon', 'sat', 'fri'}


In [11]:
day.remove('tue')
print(day)

{'wed', 'thur', 'sun', 'mon', 'sat', 'fri'}


In [12]:
day.discard('tue')
print(day)

{'wed', 'thur', 'sun', 'mon', 'sat', 'fri'}


In [13]:
day.discard('jan')
print(day)

{'wed', 'thur', 'sun', 'mon', 'sat', 'fri'}


In [14]:
day={'mon','tue','wed','thur','fri','sat','sun'}
print(day)
day.remove('tue')
print(day)
day.discard('tue')
print(day)
day.discard('jan')
print(day)

{'wed', 'tue', 'thur', 'sun', 'mon', 'sat', 'fri'}
{'wed', 'thur', 'sun', 'mon', 'sat', 'fri'}
{'wed', 'thur', 'sun', 'mon', 'sat', 'fri'}
{'wed', 'thur', 'sun', 'mon', 'sat', 'fri'}


In [15]:
day={'mon','tue','wed','thur','fri','sat','sun'}
print(day)
day.remove('wed')
day.pop()
day.discard('jan')
print(day)

{'wed', 'tue', 'thur', 'sun', 'mon', 'sat', 'fri'}
{'thur', 'sun', 'mon', 'sat', 'fri'}


### Dicitory

In [23]:
students_data={
    'ram':89,
    'mohan':67,
    'ramesh':90,
    'suresh':36
}

print(students_data['ram'])
print(students_data['suresh'])
print(students_data.get('ram'))
print(students_data.keys())
print(students_data.values())
print(students_data.items())

students_data.popitem()
print(students_data)

students_data.update({'manish':78,'preethi':98})

students_data

89
36
89
dict_keys(['ram', 'mohan', 'ramesh', 'suresh'])
dict_values([89, 67, 90, 36])
dict_items([('ram', 89), ('mohan', 67), ('ramesh', 90), ('suresh', 36)])
{'ram': 89, 'mohan': 67, 'ramesh': 90}


{'ram': 89, 'mohan': 67, 'ramesh': 90, 'manish': 78, 'preethi': 98}

In [25]:
List=[1,2,3]
dir(List)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

### IF Else Statement

## student fail or pass

In [3]:
name=input("Enter the name:")
marks=float(input("Enter your marks:"))

if marks>35:
    print(name,"is passed in the test")

else:
    print(name,"is not passed in the exam")

Enter the name: sujith
Enter your marks: 45


sujith is passed in the test


### LEAP YEAR

In [4]:
year = int(input("Enter a year: "))
if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
    print(f"{year} is a leap year.")
else:
    print(f"{year} is not a leap year.")

Enter a year:  2033


2033 is not a leap year.


In [7]:
year = int(input("Enter a year: "))
if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
    print(f"{year} is a leap year.")
else:
    print(f"{year} is not a leap year.")

Enter a year:  2024


2024 is a leap year.


### Password Check

In [6]:
gmails={'abc@gmail.com':1234, 'bbc@gmail.com':2345}

gmail=input("Enter your Gmail:")
password=int(input("Enter the password:"))

if gmails[gmail]==password:
             print("you're logged in")
else:
    print("Your Password is wrong")             

             

Enter your Gmail: bbc@gmail.com
Enter the password: 2345


you're logged in


In [8]:
gmails={'abc@gmail.com':1234, 'bbc@gmail.com':2345}

gmail=input("Enter your Gmail:")
password=int(input("Enter the password:"))

if gmails[gmail]==password:
             print("you're logged in")
else:
    print("Your Password is wrong")             

             

Enter your Gmail: abc@gmail.com
Enter the password: 1234


you're logged in


In [9]:
a=10
b=24

print("the value of a is",a,"the value b is ",b)
print(f"the value of a is {a} the value b is {b}")

the value of a is 10 the value b is  24
the value of a is 10 the value b is 24


### Elif

In [11]:
name=input("Enter the Name:")
marks=float(input("Enter your marks:"))

if marks >= 90 and marks <=100:
            print(name,'Grade:A')
elif marks >= 80 and marks <90:
            print(name,'Grade:B')
elif marks >= 70 and marks <80:
            print(name,'Grade:C')
elif marks >= 60 and marks <70:
            print(name,'Grade:D')
elif marks >= 50 and marks <60:
            print(name,'Grade:E')
elif marks >100:
            print('invaled Entry')
else:
    print(name,"Focus on studies....")

Enter the Name: sujith
Enter your marks: 85


sujith Grade:B


In [16]:
name=input("Enter the Name:")
marks=float(input("Enter your marks:"))

if marks >= 90 and marks <=100:
            print(name,'Grade:A')
elif marks >= 80 and marks <90:
            print(name,'Grade:B')
elif marks >= 70 and marks <80:
            print(name,'Grade:C')
elif marks >= 60 and marks <70:
            print(name,'Grade:D')
elif marks >= 50 and marks <60:
            print(name,'Grade:E')
elif marks >100:
            print('invalid Entry')
else:
    print(name,"Focus on studies....")

Enter the Name: sujith
Enter your marks: 112


invalid Entry


In [13]:
name=input("Enter the Name:")
marks=float(input("Enter your marks:"))

if marks >= 90 and marks <=100:
            print(name,'Grade:A')
elif marks >= 80 and marks <90:
            print(name,'Grade:B')
elif marks >= 70 and marks <80:
            print(name,'Grade:C')
elif marks >= 60 and marks <70:
            print(name,'Grade:D')
elif marks >= 50 and marks <60:
            print(name,'Grade:E')
elif marks >100:
            print('invalid Entry')
else:
    print(name,"Focus on studies....")

Enter the Name: sujith
Enter your marks: 45


sujith Focus on studies....


In [22]:
gmails={'abc@gmail.com':1234, 'sdf@gmail.com':6787}

gmail=input("Enter your gmail:")

if gmail in gmails.keys():
    password=int(input('Enter the password:'))
    if gmails[gmail]==password:
        print('user',gmail,'Logged in')
    else:
        print('password is incorrect')

else:
    print('email is not found')
    

Enter your gmail: sdf@gmail.com
Enter the password: 6787


user sdf@gmail.com Logged in


In [23]:
gmails={'abc@gmail.com':1234, 'sdf@gmail.com':6787}

gmail=input("Enter your gmail:")

if gmail in gmails.keys():
    password=int(input('Enter the password:'))
    if gmails[gmail]==password:
        print('user',gmail,'Logged in')
    else:
        print('password is incorrect')

else:
    print('email is not found')
    

Enter your gmail: abc@gmail.com
Enter the password: 34654


password is incorrect


In [24]:
gmails={'abc@gmail.com':1234, 'sdf@gmail.com':6787}

gmail=input("Enter your gmail:")

if gmail in gmails.keys():
    password=int(input('Enter the password:'))
    if gmails[gmail]==password:
        print('user',gmail,'Logged in')
    else:
        print('password is incorrect')

else:
    print('email is not found')
    

Enter your gmail: abd@gmail.com


email is not found


In [28]:
Experience=float(input('Enter you Experience:'))
degree=input('Enter you degree:')

if Experience >= 3:
    if degree == "Masters":
        print("Candidate is shortlisted for interview.")
    elif degree == "Bachelors":
         print("Candidate is on the waiting list.")
    else:
        print("candidate does not meet the education criteria.")
else:
    print("candidate lacks sufficient experience..")

Enter you Experience: 4
Enter you degree: EEE


candidate does not meet the education criteria.


### Task program

In [2]:
balances = {'Ram': 2000, 'Sujith': 1500, 'kumar': 2500}
person = input("Enter the person's name: ")
if person in balances:
    print(f"{person}: {balances[person]}")
else:
    print("Person not found.")


Enter the person's name:  Ram


Ram: 2000


In [3]:
balances = {'Ram': 2000, 'Sujith': 2500, 'kumar': 3200}
passwords = {'Ram': 'pass123', 'sujith': 'pass456', 'kumar': 'pass789'}

person = input("Enter your name: ")
if person in balances:
    password = input("Enter your password: ")
    if password == passwords[person]:
        choice = input("Enter your choice (withdraw, balance, deposit): ").lower()
        if choice == "withdraw":
            amount = float(input("Enter amount to withdraw: "))
            if amount <= balances[person]:
                balances[person] -= amount
                print(f"Withdrawal successful. New balance: {balances[person]}")
            else:
                print("Insufficient balance.")
        elif choice == "balance":
            print(f"Your balance is: {balances[person]}")
        else:  
            amount = float(input("Enter amount to deposit: "))
            balances[person] += amount
            print(f"Deposit successful. New balance: {balances[person]}")
    else:
        print("Incorrect password.")
else:
    print("Person not found.")


Enter your name:  Ram
Enter your password:  pass123
Enter your choice (withdraw, balance, deposit):  withdraw
Enter amount to withdraw:  13


Withdrawal successful. New balance: 1987.0


#### while true

In [ ]:
while True:
    print("Menu:")
    print("1. meals")
    print("2. biriyani")
    print("3. fried rice")
    print("4. ghee rice")
    print("5. Exit")

    choice = int(input("choose an option(1,2,3,4,5):"))

    if choice == 1:
        print("Your order meals is placed")
    elif choice == 2:
        print("Your order biriyani is placed")
    elif choice == 3:
        print("Your order fried rice is placed")
    elif choice == 4:
        print("Your order ghee rice is placed")
    elif choice == 5:
    
        print("Exit")
        break
    
    else:
        print(" invalued choice.please try again.")

Menu:
1. meals
2. biriyani
3. fried rice
4. ghee rice
5. Exit


### For Loop

In [2]:
print(list(range(10)))
print(list(range(1,11)))
print(list(range(0,-10,-1)))
print(list(range(0,10,2)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[0, -1, -2, -3, -4, -5, -6, -7, -8, -9]
[0, 2, 4, 6, 8]


In [5]:
table = int(input("Enter the table"))
for i in range(1,21):
    print(f"{table}*{i}={table*i}")

Enter the table 2


2*1=2
2*2=4
2*3=6
2*4=8
2*5=10
2*6=12
2*7=14
2*8=16
2*9=18
2*10=20
2*11=22
2*12=24
2*13=26
2*14=28
2*15=30
2*16=32
2*17=34
2*18=36
2*19=38
2*20=40


### Iterating over list

In [6]:
cuisine=["indian","chinese","italian"]
for i in cuisine:
    print(i)

indian
chinese
italian


In [7]:
for i in range(1, 11):  
    for j in range(1, 11): 
        print(f"{i} x {j} = {i * j}")  
    print()

1 x 1 = 1
1 x 2 = 2
1 x 3 = 3
1 x 4 = 4
1 x 5 = 5
1 x 6 = 6
1 x 7 = 7
1 x 8 = 8
1 x 9 = 9
1 x 10 = 10

2 x 1 = 2
2 x 2 = 4
2 x 3 = 6
2 x 4 = 8
2 x 5 = 10
2 x 6 = 12
2 x 7 = 14
2 x 8 = 16
2 x 9 = 18
2 x 10 = 20

3 x 1 = 3
3 x 2 = 6
3 x 3 = 9
3 x 4 = 12
3 x 5 = 15
3 x 6 = 18
3 x 7 = 21
3 x 8 = 24
3 x 9 = 27
3 x 10 = 30

4 x 1 = 4
4 x 2 = 8
4 x 3 = 12
4 x 4 = 16
4 x 5 = 20
4 x 6 = 24
4 x 7 = 28
4 x 8 = 32
4 x 9 = 36
4 x 10 = 40

5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
5 x 10 = 50

6 x 1 = 6
6 x 2 = 12
6 x 3 = 18
6 x 4 = 24
6 x 5 = 30
6 x 6 = 36
6 x 7 = 42
6 x 8 = 48
6 x 9 = 54
6 x 10 = 60

7 x 1 = 7
7 x 2 = 14
7 x 3 = 21
7 x 4 = 28
7 x 5 = 35
7 x 6 = 42
7 x 7 = 49
7 x 8 = 56
7 x 9 = 63
7 x 10 = 70

8 x 1 = 8
8 x 2 = 16
8 x 3 = 24
8 x 4 = 32
8 x 5 = 40
8 x 6 = 48
8 x 7 = 56
8 x 8 = 64
8 x 9 = 72
8 x 10 = 80

9 x 1 = 9
9 x 2 = 18
9 x 3 = 27
9 x 4 = 36
9 x 5 = 45
9 x 6 = 54
9 x 7 = 63
9 x 8 = 72
9 x 9 = 81
9 x 10 = 90

10 x 1 = 10
10 

In [8]:
programminglanguages = {'j':'java','p':'python'}
for key,value in programminglanguages.items():
    print(f'key:{key},programminglanguage:{value}')

key:j,programminglanguage:java
key:p,programminglanguage:python


In [1]:
list_of_lists = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
flattened_list = []

for sublist in list_of_lists:
    for item in sublist:
        flattened_list.append(item)

print(flattened_list)


[1, 2, 3, 4, 5, 6, 7, 8, 9]


### Function in python

In [2]:
def greet():
    print("Welcome to programming world")

In [3]:
greet()

Welcome to programming world


In [7]:
def greet(name):
    print("Hello",name)

In [8]:
greet("sujith")

Hello sujith


### Positional arguement

In [11]:
def sum(a,b):
    sum=a+b
    return sum

sum(9,6)

15

In [13]:
def user_info(email,username):
    print(f"username:{username}")
    print(f"Email:{email}")

user_info("ramesh1234@gmail.com","ramesh")

username:ramesh
Email:ramesh1234@gmail.com


#### KEYWORD ARGUMENT

In [14]:
def info(name,age,place):
    print(f"Employee name is {name}")
    print(f"age is {age}")
    print(f"place is {place}")

info(name="sujith" ,place="Chennai", age=21)

Employee name is sujith
age is 21
place is Chennai


### Variable length arguments

In [16]:
def sum1(*values):
    sum2=0
    for i in values:
        sum2=sum2+i
    return sum2

sum1(4,5,6,7,8,9)

39

In [17]:
def students(schoolname,grade,*name):
    for i in name:
        print(f"{i} studying in {schoolname} at grade {grade}")

students('psy',3,'ram','suresh','ramesh')

ram studying in psy at grade 3
suresh studying in psy at grade 3
ramesh studying in psy at grade 3


In [21]:
def log_message(level,*messages):
    print(f"[{level}]",end="")
    for message in messages:
        print(message, end=" ")

log_message("info", "user logged in", "from IP 192.168.1.1")

[info]user logged in from IP 192.168.1.1 

#### default parametey

In [22]:
def sum(a=7,b=10):
    c=a+b
    return c

sum(a=10,b=23)

33

In [1]:
import datetime as dt
dt.date.today()

datetime.date(2025, 4, 9)

### Library Management

In [7]:
class library:
    def __init__(self):
        self.name=['story','horror','science','arts']

    def add_books(self):
        self.add_book=input('Enter the book name:')
        self.name.append(self.add_book)
        print(f'The book {self.add_book} was added sucessfully on {dt.date.today()}')

    def borrow_book(self):
        name1=input('Enter the book name:')
        self.take_book=input('Enter the book name:')
        if self.take_book in self.name:

            self.name.remove(self.take_book)
            print(f'book {self.take_book} borrowed by {name1} at {dt.date.today()}')

        else:
            print('It seems the book you entered is not available')

    def available_book(self):
        if self.name: # True if we have some values inside the list
                      #false if we don't have any values inside the list 
            for i in self.name:#['story','horror','science','arts']
                print(i)

            print('\n')

        else:
            print('There is no books')

    def return_books(self):
        self.add_=input('Enter the book name')
        self.name.append(self.add_)
        print(f"book {self.add_} is returned sucessfully")

def main():
    objective1=library()
    while True:
        print('Library Management system')
        print('Enter 1 to check avaliable book')
        print('Enter 2 to borrow book')
        print('Enter 3 to return book')
        print('Enter 4 to add new book')
        print('Enter 5 to Exit')
        print('\n')

    
        a=int(input('Enter the choice'))

        if a==1:
            objective1.available_book()

        elif a==2:
            objective1.borrow_book

        elif a==3:
             objective1.return_books()

        elif a==4:
            objective1.add_books()

        elif a==5:
            print("Thank you visit again")
            break

        else:
            print("invalid entry , try again")

main()
            
           

        


Library Management system
Enter 1 to check avaliable book
Enter 2 to borrow book
Enter 3 to return book
Enter 4 to add new book
Enter 5 to Exit




Enter the choice 1


story
horror
science
arts


Library Management system
Enter 1 to check avaliable book
Enter 2 to borrow book
Enter 3 to return book
Enter 4 to add new book
Enter 5 to Exit




Enter the choice 2


Library Management system
Enter 1 to check avaliable book
Enter 2 to borrow book
Enter 3 to return book
Enter 4 to add new book
Enter 5 to Exit




Enter the choice 3
Enter the book name arts


book arts is returned sucessfully
Library Management system
Enter 1 to check avaliable book
Enter 2 to borrow book
Enter 3 to return book
Enter 4 to add new book
Enter 5 to Exit




Enter the choice 4
Enter the book name: Kannishkar


The book Kannishkar was added sucessfully on 2025-04-09
Library Management system
Enter 1 to check avaliable book
Enter 2 to borrow book
Enter 3 to return book
Enter 4 to add new book
Enter 5 to Exit




Enter the choice 5


Thank you visit again


In [4]:
class Bank:
    def __init__(self, initial_balance, password):
        self.balance = initial_balance
        self.password = password

    def verify_password(self, input_password):
        return self.password == input_password

    def deposit(self, amount, input_password):
        if self.verify_password(input_password):
            if amount > 0:
                self.balance += amount
                print(f"Deposited ₹{amount}. New balance: ₹{self.balance}")
            else:
                print("Invalid deposit amount.")
        else:
            print("Incorrect password. Access denied.")

    def withdraw(self, amount, input_password):
        if self.verify_password(input_password):
            if 0 < amount <= self.balance:
                self.balance -= amount
                print(f"Withdrawn ₹{amount}. New balance: ₹{self.balance}")
            else:
                print("Invalid amount or insufficient balance.")
        else:
            print("Incorrect password. Access denied.")

    def check_balance(self, input_password):
        if self.verify_password(input_password):
            print(f"Current balance: ₹{self.balance}")
        else:
            print("Incorrect password. Access denied.")


# Example usage:
my_account = Bank(initial_balance=1000, password="secure123")

# Operations
my_account.deposit(500, "secure123")      # Correct password
my_account.withdraw(300, "secure123")     # Correct password
my_account.check_balance("wrongpass")     # Incorrect password


Deposited ₹500. New balance: ₹1500
Withdrawn ₹300. New balance: ₹1200
Incorrect password. Access denied.


### Numpy

In [7]:
import numpy as np
import sys
import time

### Import  Necessary Libraries

In [4]:
a=[1,2,3,4]
b=[3,4,5,6]
c=[]
for i in range (0,len(a)):
   c.append(a[i]+b[i])

c

[4, 6, 8, 10]

In [7]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
a+b

array([ 6,  8, 10, 12])

### Multidimesnsional array

In [11]:
a1=np.array([1,2,3,4,5,6])
b2=np.array([2,3,4,2,3,4])
print(a1.ndim)

a2=np.array([[1,2,3],
             [4,5,6]])
b2=np.array([[2,3],
             [3,2]])

print(a2.ndim)

b3=np.array([[[2,3],[3,2]],[[5,3],[6,2]]])
b3.ndim

1
2


3

### for one dimensional array

In [9]:
a=np.array([1,2,3,4,5,6])


print("Maximum value in the array" ,a.max())
print("minimum value in the array" ,a.min())
print ("mean value", a.mean())
print ("Sum of the array",a. sum())
print("product of the array",a. prod())
print("Index of the minimum value",a. argmin())
print("Index of the maximum value" ,a.argmax())
print("To check the dimension of the array",a.ndim)
print("To check the shape of the array",a. shape)
print("To check the datatype of the array" ,a.dtype)
print("To check the shape of the array",a.size)

Maximum value in the array 6
minimum value in the array 1
mean value 3.5
Sum of the array 21
product of the array 720
Index of the minimum value 0
Index of the maximum value 5
To check the dimension of the array 1
To check the shape of the array (6,)
To check the datatype of the array int32
To check the shape of the array 6


####  For two dimensional array

In [11]:
a_2d=np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print("To check the shape of the array",a_2d.shape)

To check the shape of the array (3, 3)


In [12]:
a_2d.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [13]:
a_2d.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
b=np.array([2,3,4,2,3,4])

print(b.reshape(3,2))
b.reshape(2,3)

[[2 3]
 [4 2]
 [3 4]]


array([[2, 3, 4],
       [2, 3, 4]])

### reason why list is slow as compared to Numpy

In [16]:
List=['a',1,3.2]
print(List)

a=np.array([1,2.2,3])
a

['a', 1, 3.2]


array([1. , 2.2, 3. ])

### Basic operation in numpy

In [17]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.ones((3,4),dtype='int64')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int64)

### Slicing the array in numpy

In [19]:
a=[1,2,3,4,5]
a[0:7:3]

[1, 4]

In [20]:
a=np.array([1,2,3,4,5,6,7,8])
print(a[1])
print(a[1:6:2])
print(a[0:3])
print(a[-1])
print(a[-3:-1])
print(a[-4])

2
[2 4 6]
[1 2 3]
8
[6 7]
5


In [22]:
a=np.array([[12,34,54],#0
            [34,21,56],#1
            [23,87,89]])#2
print(a[1,1])
print(a[0,0:2])
print(a[0:3,1])
print(a[0:2,0:2])


21
[12 34]
[34 21 87]
[[12 34]
 [34 21]]


### Python list vs numpy

### size comparision b/w numpy and list

In [10]:
l=list(range(1000))
print("shape of python list",sys.getsizeof(9)*len(l))

a=np.arange(1000)
print("shape of numpy array",a.itemsize*len(a))

shape of python list 28000
shape of numpy array 4000


### Computation time for array and list

In [12]:
import time

In [15]:
start=time.time()

a=list(range(100000))
c=[]
for i in a:
    c.append(i**2)

end=time.time()

end-start
    

0.040463924407958984

In [17]:
import numpy as np
size=10000
a1=np.arange(size)
a2=np.arange(size)

start=time.time()
result=a1+a2
end=time.time()
print("time taken by array",end-start)

time taken by array 0.0


In [20]:
arr=np.array([1,4,9,16,25])

sqrt_arr=np.sqrt(arr)
print("square root:",sqrt_arr)

log_arr=np.log(arr)
print("log:",log_arr)

sin_arr=np.sin(arr)
print("sine:",sin_arr)

abs_arr=np.abs(np.array([-1,-4,3,-2]))
print("absolute:",abs_arr)

square root: [1. 2. 3. 4. 5.]
log: [0.         1.38629436 2.19722458 2.77258872 3.21887582]
sine: [ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]
absolute: [1 4 3 2]
